### ISSUE TITLE
MiniAVC not need in BAM-1.8.0-1.3.3.3.zip

### ISSUE THREAD

**Issue by aezarkones** [linuxgurugamer/CIT#1]
No need for GameData\BAM\MiniAVC.dll file causing some errors in new versions. Works fine when you remove MiniAVC using https://github.com/linuxgurugamer/QuickMods/releases/tag/QuickSearch-3.3.0.10 on KSP 1.11.1

**Comment by linuxgurugamer** [comment]
Next time this gets released, it will be removed.
Until then, use ZeroMiniAVC as recommended
